(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-answer/qui-answer"],{2432:function(e,t,n){"use strict";var i=n("889f"),u=n.n(i);u.a},"4f70":function(e,t,n){"use strict";n.r(t);var i=n("c829"),u=n("5502");for(var r in u)"default"!==r&&function(e){n.d(t,e,(function(){return u[e]}))}(r);n("2432");var o,a=n("f0c5"),s=Object(a["a"])(u["default"],i["b"],i["c"],!1,null,"36a12f78",null,!1,i["a"],o);t["default"]=s.exports},5471:function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var i=n("6c07"),u=r(n("c939"));function r(e){return e&&e.__esModule?e:{default:e}}var o={mixins:[u.default],props:{userRole:{type:Array,default:function(){return[]}},userId:{type:[Number,String],default:""},avatarUrl:{type:String,default:""},userName:{type:String,default:""},isReal:{type:Boolean,default:!1},answerContent:{type:String,default:""},themeTime:{type:String,default:""},imagesList:{type:Array,default:function(){return[]}},isOnlooker:{type:Boolean,default:!1},thread:{type:Object,default:function(){return{paidCount:0,paidUsers:[],payment:0}}}},data:function(){return{paymentAnswer:"1",payNum:"1234",personRes:[],payment:2,list:[],listBg:"var(--qui-BG-ED)",iosShow:!0}},computed:{localTime:function(){return(0,i.time2DateAndHM)(this.themeTime?this.themeTime:"")}},created:function(){var t=e.getSystemInfoSync();this.system=t.platform,"ios"===this.system&&(console.log("当前是iOS"),this.iosShow=!1)},methods:{personJump:function(t){this.$store.getters["session/get"]("isLogin")||this.mpLoginMode(),t<=0||e.navigateTo({url:"/pages/profile/index?userId=".concat(t)})},btnClick:function(e){this.$emit("btnClick",e)}}};t.default=o}).call(this,n("543d")["default"])},5502:function(e,t,n){"use strict";n.r(t);var i=n("5471"),u=n.n(i);for(var r in i)"default"!==r&&function(e){n.d(t,e,(function(){return i[e]}))}(r);t["default"]=u.a},"889f":function(e,t,n){},c829:function(e,t,n){"use strict";n.d(t,"b",(function(){return u})),n.d(t,"c",(function(){return r})),n.d(t,"a",(function(){return i}));var i={quiTopicHeader:function(){return Promise.all([n.e("common/vendor"),n.e("components/qui-topic-header/qui-topic-header")]).then(n.bind(null,"3a0d"))},quiUparse:function(){return Promise.all([n.e("common/vendor"),n.e("components/qui-uparse/qui-uparse")]).then(n.bind(null,"11a7"))},quiImage:function(){return n.e("components/qui-image/qui-image").then(n.bind(null,"991d"))},quiPersonList:function(){return n.e("components/qui-person-list/qui-person-list").then(n.bind(null,"77ee"))}},u=function(){var e=this,t=e.$createElement,n=(e._self._c,e.i18n.t("topic.pay")),i=e.i18n.t("topic.paymentAnswer"),u=e.i18n.t("topic.visible");e.$mp.data=Object.assign({},{$root:{g0:n,g1:i,g2:u}})},r=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-answer/qui-answer-create-component',
    {
        'components/qui-answer/qui-answer-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("4f70"))
        })
    },
    [['components/qui-answer/qui-answer-create-component']]
]);
