(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-report/qui-report"],{"00ac":function(t,e,r){"use strict";var n;r.d(e,"b",(function(){return o})),r.d(e,"c",(function(){return a})),r.d(e,"a",(function(){return n}));var o=function(){var t=this,e=t.$createElement;t._self._c},a=[]},"6cdc":function(t,e,r){"use strict";r.r(e);var n=r("e02b"),o=r.n(n);for(var a in n)"default"!==a&&function(t){r.d(e,t,(function(){return n[t]}))}(a);e["default"]=o.a},"90aa":function(t,e,r){},c546:function(t,e,r){"use strict";var n=r("90aa"),o=r.n(n);o.a},d818:function(t,e,r){"use strict";r.r(e);var n=r("00ac"),o=r("6cdc");for(var a in o)"default"!==a&&function(t){r.d(e,t,(function(){return o[t]}))}(a);r("c546");var i,u=r("f0c5"),s=Object(u["a"])(o["default"],n["b"],n["c"],!1,null,"271bc36f",null,!1,n["a"],i);e["default"]=s.exports},e02b:function(t,e,r){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r={props:{currentLoginId:{default:0,type:Number},threadId:{default:"",type:String},commentId:{default:"",type:String},reportType:{default:0,type:Number}},data:function(){return{reportData:[{value:"advertisingRubbish",name:"广告垃圾"},{value:"illegalContent",name:"违规内容"},{value:"maliciousIrrigation",name:"恶意灌水"},{value:"repeatPost",name:"重复发帖"},{value:"other",name:"其他"}],currentReport:"",otherReasonValue:""}},computed:{r:function(){return this.i18n.t("report")}},methods:{reportRadioChange:function(t){this.currentReport=t.target.value},reportTextareaInput:function(t){this.otherReasonValue=t.detail.value},reportConfirmClick:function(){var e=this;if(this.currentReport){var r="";if("other"===this.currentReport){if(!this.otherReasonValue)return void t.showToast({icon:"none",title:this.i18n.t("report.enterOtherReason")});r=this.otherReasonValue}else this.reportData.forEach((function(t){t.value===e.currentReport&&(r=t.name)}));var n=null;n=1===this.reportType?{_jv:{type:"reports"},user_id:this.currentLoginId,thread_id:parseInt(this.threadId,10),type:this.reportType,reason:"".concat(r)}:{_jv:{type:"reports"},user_id:this.currentLoginId,thread_id:parseInt(this.threadId,10),post_id:parseInt(this.commentId,10),type:this.reportType,reason:"".concat(r)},this.$store.dispatch("jv/post",n).then((function(r){r._jv&&(e.$emit("reportClose"),t.showToast({icon:"none",title:e.i18n.t("report.reportSucceed")}))}))}else t.showToast({icon:"none",title:this.i18n.t("report.pleaseClickReasons")})},reportCancelClick:function(){this.otherReasonValue="",this.currentReport="",this.$emit("reportClose")}}};e.default=r}).call(this,r("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-report/qui-report-create-component',
    {
        'components/qui-report/qui-report-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("d818"))
        })
    },
    [['components/qui-report/qui-report-create-component']]
]);
