(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-audio/qui-audio"],{"196e":function(t,i,n){"use strict";var u=n("d3a3"),e=n.n(u);e.a},2068:function(t,i,n){"use strict";n.r(i);var u=n("d66a"),e=n("a8bd");for(var a in e)"default"!==a&&function(t){n.d(i,t,(function(){return e[t]}))}(a);n("196e");var o,d=n("f0c5"),r=Object(d["a"])(e["default"],u["b"],u["c"],!1,null,"d0b1c150",null,!1,u["a"],o);i["default"]=r.exports},"2caa":function(t,i,n){"use strict";(function(t){Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var n={props:{src:{type:String,default:""},audioId:{type:String,default:""},autoplay:{type:Boolean,default:!1},name:{type:String,default:""},canPlay:{type:Boolean,default:!0},color:{type:String,default:"#1878f3"}},data:function(){return{audio:null,currentTime:"00 : 00",duration:"00 : 00",durationTime:0,current:"",loading:!1,paused:!0,seek:!1}},watch:{current:function(t){t&&(this.currentTime=this.format(t))}},mounted:function(){},destroyed:function(){this.audio&&this.audio.destroy()},methods:{initAudio:function(){var i=this;this.audio=t.createInnerAudioContext(),this.audio.src=this.src,this.loading=!0,this.audio.onTimeUpdate((function(){i.durationTime||i.setDuration(),i.seek||(i.current=i.audio.currentTime)})),this.audio.onPlay((function(){i.paused=!1})),this.audio.onPause((function(){i.paused=!0})),this.audio.onEnded((function(){i.paused=!0,i.current=0,i.currentTime="00 : 00"})),this.audio.onSeeked((function(){i.seek=!1}))},operation:function(){this.canPlay&&(this.audio||this.initAudio(),this.paused?(this.audio.play(),this.$emit("audioPlay",this.audioId)):this.audio.pause())},audioPause:function(){this.paused&&!this.loading||this.audio.pause()},format:function(t){if(t)return"".concat("0".repeat(2-String(Math.floor(t/60)).length)+Math.floor(t/60),":").concat("0".repeat(2-String(Math.floor(t%60)).length)).concat(Math.floor(t%60))},change:function(t){this.audio.seek(t.detail.value)},setDuration:function(){this.duration=this.format(this.audio.duration),this.durationTime=this.audio.duration,this.loading=!1},fileClick:function(){this.$emit("fileClick")}}};i.default=n}).call(this,n("543d")["default"])},a8bd:function(t,i,n){"use strict";n.r(i);var u=n("2caa"),e=n.n(u);for(var a in u)"default"!==a&&function(t){n.d(i,t,(function(){return u[t]}))}(a);i["default"]=e.a},d3a3:function(t,i,n){},d66a:function(t,i,n){"use strict";n.d(i,"b",(function(){return e})),n.d(i,"c",(function(){return a})),n.d(i,"a",(function(){return u}));var u={quiIcon:function(){return n.e("components/qui-icon/qui-icon").then(n.bind(null,"d13f"))}},e=function(){var t=this,i=t.$createElement;t._self._c;t._isMounted||(t.e0=function(i){t.seek=!0,t.current=i.detail.value})},a=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-audio/qui-audio-create-component',
    {
        'components/qui-audio/qui-audio-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("2068"))
        })
    },
    [['components/qui-audio/qui-audio-create-component']]
]);
