(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-avatar/qui-avatar"],{"109d":function(t,e,n){},"1a8a":function(t,e,n){"use strict";var r=n("109d"),a=n.n(r);a.a},"7a5a":function(t,e,n){"use strict";n.r(e);var r=n("9f5d"),a=n("f653");for(var i in a)"default"!==i&&function(t){n.d(e,t,(function(){return a[t]}))}(i);n("1a8a");var u,s=n("f0c5"),o=Object(s["a"])(a["default"],r["b"],r["c"],!1,null,"2dc85646",null,!1,r["a"],u);e["default"]=o.exports},"9f5d":function(t,e,n){"use strict";var r;n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return r}));var a=function(){var t=this,e=t.$createElement;t._self._c},i=[]},d229:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=a(n("1d37"));function a(t){return t&&t.__esModule?t:{default:t}}var i={100:"font-size: 24px;line-height: 80rpx;",80:"font-size: 24px;line-height: 80rpx;",70:"font-size: 22px;line-height: 70rpx;",60:"font-size: 20px;line-height: 60rpx;",50:"font-size: 18px;line-height: 50rpx;"},u={props:{user:{type:[Object,String],default:function(){return{}}},size:{type:[Number,String],default:80},isReal:{type:Boolean,default:!1}},data:function(){return{styleText:"",userInfo:""}},computed:{avatarUrl:function(){return this.user.avatarUrl&&0!==this.user.avatarUrl.indexOf("/static/noavatar.gif")},usernameAt:function(){return this.user.username?this.user.username.charAt(0).toUpperCase():this.i18n.t("core.noavatar")}},mounted:function(){this.styleText=this.style();var t=this.$store.getters["session/get"]("userId");if(t){var e=this.$store.getters["jv/get"]("users/".concat(t));this.userInfo=e}},methods:{style:function(){var t=(0,r.default)(this.usernameAt);return"background-color: #".concat(t,";").concat(i[this.size])},error:function(){this.user.avatarUrl=!1},click:function(){this.$emit("click")}}};e.default=u},f653:function(t,e,n){"use strict";n.r(e);var r=n("d229"),a=n.n(r);for(var i in r)"default"!==i&&function(t){n.d(e,t,(function(){return r[t]}))}(i);e["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-avatar/qui-avatar-create-component',
    {
        'components/qui-avatar/qui-avatar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("7a5a"))
        })
    },
    [['components/qui-avatar/qui-avatar-create-component']]
]);
