(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-header/qui-header"],{"1d85":function(t,e,n){"use strict";var u=n("4c83"),o=n.n(u);o.a},"324c":function(t,e,n){"use strict";n.r(e);var u=n("8fe8"),o=n.n(u);for(var i in u)"default"!==i&&function(t){n.d(e,t,(function(){return u[t]}))}(i);e["default"]=o.a},"4c83":function(t,e,n){},"8fe8":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var u="header-h5";u="";var o={name:"QuiHeader",props:{headImg:{type:String,default:""},backgroundHeadFullImg:{type:String,default:""},themeNum:{type:[Number,String],default:0},homecontent:{type:String,default:""},iconcolor:{type:String,default:"#fff"},postNum:{type:[Number,String],default:0},share:{type:String,default:""},shareBtn:{type:String,default:""},shareShow:{type:Boolean,default:!1},title:{type:String,default:""},isShowBack:{type:Boolean,default:!0},isShowHome:{type:Boolean,default:!0},isShowMore:{type:Boolean,default:!0},color:{type:String,default:""}},data:function(){return{headerH5:u}},computed:{t:function(){return this.i18n.t("home")}},onLond:function(){},methods:{open:function(t){this.$emit("click",t)},closeShare:function(t){this.$emit("closeShare",t)},logoClick:function(t){this.$emit("logoClick",t)}}};e.default=o},"9dfa":function(t,e,n){"use strict";n.r(e);var u=n("d21b"),o=n("324c");for(var i in o)"default"!==i&&function(t){n.d(e,t,(function(){return o[t]}))}(i);n("1d85");var r,a=n("f0c5"),c=Object(a["a"])(o["default"],u["b"],u["c"],!1,null,null,null,!1,u["a"],r);e["default"]=c.exports},d21b:function(t,e,n){"use strict";n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return u}));var u={quiIcon:function(){return n.e("components/qui-icon/qui-icon").then(n.bind(null,"d13f"))}},o=function(){var t=this,e=t.$createElement;t._self._c},i=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-header/qui-header-create-component',
    {
        'components/qui-header/qui-header-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("9dfa"))
        })
    },
    [['components/qui-header/qui-header-create-component']]
]);
